"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from speakeasy_client_sdk_python.types import BaseModel
from typing_extensions import TypedDict


class ErrorTypedDict(TypedDict):
    r"""The `Status` type defines a logical error model"""

    message: str
    r"""A developer-facing error message."""
    status_code: int
    r"""The HTTP status code"""


class Error(BaseModel):
    r"""The `Status` type defines a logical error model"""

    message: str
    r"""A developer-facing error message."""

    status_code: int
    r"""The HTTP status code"""
