"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from .basemodel import (
    BaseModel,
    Nullable,
    OptionalNullable,
    UnrecognizedInt,
    UnrecognizedStr,
    UNSET,
    UNSET_SENTINEL,
)

from .errors import (
    APIConnectionError,
    SDKError,
    BadRequestError,
    UnauthorizedError,
    ForbiddenError,
    NotFoundError,
    MethodNotAllowedError,
    UnprocessableEntityError,
    RateLimitError,
    InternalServerError,
    BadGatewayError,
    ServiceUnavailableError,
    get_api_error,
)

__all__ = [
    "APIConnectionError",
    "SDKError",
    "BadRequestError",
    "UnauthorizedError",
    "ForbiddenError",
    "NotFoundError",
    "MethodNotAllowedError",
    "UnprocessableEntityError",
    "RateLimitError",
    "InternalServerError",
    "BadGatewayError",
    "ServiceUnavailableError",
    "BaseModel",
    "Nullable",
    "OptionalNullable",
    "UnrecognizedInt",
    "UnrecognizedStr",
    "UNSET",
    "UNSET_SENTINEL",
    "get_api_error",
]
